// Words and phrases that indicate ambiguity in meeting notes.
// Add more entries here as needed.
export const AMBIGUOUS_WORDS = [
  // Vague ownership
  'someone',
  'somebody',
  'anyone',
  'anybody',
  'everyone',
  'everybody',
  'they',
  'we',
  'the team',
  'whoever',
  'the group',
  'people',
  'folks',
  'the guys',
  'management',
  'leadership',

  // Vague time / urgency
  'soon',
  'later',
  'asap',
  'eventually',
  'sometime',
  'shortly',
  'tomorrow',
  'next week',
  'next month',
  'next quarter',
  'in the future',
  'at some point',
  'someday',
  'one day',
  'whenever',
  'end of day',
  'end of week',
  'end of month',
  'by then',
  'before long',
  'in a bit',
  'real soon',
  'near term',
  'long term',
  'down the road',
  'in due time',
  'in due course',

  // Hedging / uncertainty
  'maybe',
  'perhaps',
  'possibly',
  'probably',
  'might',
  'could',
  'should',
  'would',
  'ideally',
  'hopefully',
  'if possible',
  'try to',
  'try and',
  'attempt to',
  'we can',
  'we should',
  'we might',
  'we could',
  'might want to',
  'could potentially',
  'would be good',
  'would be nice',
  'would be great',

  // Vague scope / effort
  'a few',
  'some',
  'several',
  'a couple',
  'various',
  'many',
  'a lot',
  'numerous',
  'enough',
  'sufficient',
  'appropriate',
  'adequate',
  'reasonable',
  'better',
  'improve',
  'fix',
  'handle',
  'deal with',
  'look into',
  'look at',
  'check on',
  'follow up',
  'circle back',
  'touch base',
  'sync up',
  'revisit',
  'take a look',
  'figure out',
  'sort out',
  'work on',
  'take care of',
  'address',

  // Vague completion / outcome
  'done',
  'finished',
  'ready',
  'complete',
  'good enough',
  'mostly',
  'almost',
  'nearly',
  'kind of',
  'sort of',
  'basically',
  'roughly',
  'approximately',
  'around',
  'about',
]

/**
 * Returns a deduplicated list of ambiguous words found in the given text.
 * Pass a custom wordList to use a per-user word set instead of the default.
 */
export function detectAmbiguity(text, wordList = AMBIGUOUS_WORDS) {
  return wordList.filter((word) => {
    const escaped = word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    return new RegExp(`\\b${escaped}\\b`, 'i').test(text)
  })
}
